### ISSUE TITLE
how to profile petals inference time cost

### ISSUE THREAD

**Issue by mabuyun** [bigscience-workshop/petals#240]
Hello all,

I launch my own swarm on 24 computers according to [Launch-your-own-swarm](https://github.com/bigscience-workshop/petals/wiki/Launch-your-own-swarm) . 
Each computer has 1 gpu and 32GB memory, and contains 3 blocks of petals-bloom.

It works fine but takes a long time to inference once.

Follow `Use the model`, I only inference bloom without train the model. 

```
import torch
import torch.nn.functional as F
import transformers
from src import DistributedBloomForCausalLM

initial_peers = [TODO_put_one_or_more_server_addresses_here]  # e.g. ["/ip4/127.0.0.1/tcp/more/stuff/here"]
tokenizer = transformers.BloomTokenizerFast.from_pretrained("bigscience/bloom-petals")
model = DistributedBloomForCausalLM.from_pretrained(
  "bigscience/bloom-petals", initial_peers=initial_peers, low_cpu_mem_usage=True, torch_dtype=torch.float32
)

inputs = tokenizer("a cat sat", return_tensors="pt")["input_ids"]
# use max_new_tokens instead of max_length 
remote_outputs = model.generate(inputs, max_new_tokens=50)
print(tokenizer.decode(remote_outputs[0]))
```

I tried different max_new_tokens values, and the time-consuming almost 2s/token

Is there a way to profile the inference performance , i wonder why it is so slow

Thanks

**Comment by borzunov** [comment]
Hi @mabuyun!

Sorry for the delayed response.

**Heads up:** Please note that Petals promises the speed of ~1 sec/token for most cases. You can tune your setup to get ~0.7 sec/token, but you're unlikely to get a much better speed due to the large model size and the connection latency, so don't expect anything like ~10x improvement. Below, I'll only talk about ways to improve the speed from ~2 sec/token to 0.7-1 sec/token.

Before starting, make sure you use the **latest version** of Petals from this repository (not from PyPI) or the latest image from Docker Hub. I ask for that because we've recently merged some changes speeding up inference by ~30%. We expect another 30% speedup once #226 is implemented, but this would take a month or two on our side.

Apparently, the inference is slow in your case because each of your servers holds too few blocks, so the client needs to ask all the 24 servers one by one to generate each new token. Could you please clarify **how much GPU memory do your servers have?** You mentioned the "32 GB memory", but I'm not sure if you're talking about RAM or GPU memory. If it's the GPU memory, each of your server can host ~10 blocks, so the client will only need 7 hops (instead of 24 hops) and will get much better inference speed.

In case each server can indeed hold only 3 blocks (e.g., if they have only ~10 GB GPU memory each):

- Please note that the client is waiting for packet round trips most of the time, so you can improve the speed by minimizing the latency. In the best case, the client should be located in the same data center (or at least the same city/country) where your servers are.

- Alternatively, you can consider replacing some of the servers with machines with more GPU memory, so that you need less hops between servers during inference.

- Alternatively, you can consider using multi-GPU servers and tensor parallelism (so that a server running on a multi-GPU machine becomes very fast due to using all GPUs in parallel). Let me know if this is an option for you, I'll provide more instructions for this case.

**Comment by mabuyun** [comment]
Hi @borzunov ,

I want to try using multi-GPU servers and tensor parallelism.

**Comment by borzunov** [comment]
@mabuyun,

Please try this:

1. Install the latest version of Petals from the repo: `pip install git+https://github.com/bigscience-workshop/petals`
2. Run the server with the options `--load_in_8bit True --tensor_parallel_devices cuda:0 cuda:1` (if you have more than two GPUs, add more `cuda:N` args here).
3. Let us know what speed you got in this case.

**Heads-up:** tensor parallelism is an experimental feature that doesn't work well on all GPUs yet, so sometimes you may actually end up with a slower speed. We plan to ship some fixes this month so that it gives a larger speedup on more types of GPUs.

**Comment by mabuyun** [comment]
@borzunov 

I got a runtime error when try using multi-GPU servers and tensor parallelism.
```
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
```

I prepared 18 computers for testing, each computer has 2 2080ti gpus and 32GB RAM. Each 2080ti has ~11 GB GPU memory.
Each computer runs 4 blocks,  and only the last computer runs 2 blocks(68,69).
Petals on each machine has been upgraded by this cmd: `pip install git+https://github.com/bigscience-workshop/petals`

Here is my start cmd
```
export CUDA_VISIBLE_DEVICES=0,1
PETALS_8BIT_BACKWARD=1
COMPRESSION=NONE
CACHE_SIZE="1.0GiB"
PORT=0
START_IDX=$1 
END_IDX=`expr $START_IDX + 4`
if [ $END_IDX -gt 70 ]; then
    END_IDX=70
fi

python3 -m petals.cli.run_server bigscience/bloom-petals --throughput 150 --attn_cache_size $CACHE_SIZE  --host_maddrs /ip4/0.0.0.0/tcp/$PORT --initial_peers /ip4/x.x.x.x/tcp/x/p2p/xxxx --compression $COMPRESSION --load_in_8bit True --torch_dtype float16 --tensor_parallel_devices cuda:0 cuda:1 --block_indices $START_IDX:$END_IDX 
```

All blocks have been loaded  and servers have been started.


Then I run this script
```
import torch
import torch.nn.functional as F
import transformers
from src import DistributedBloomForCausalLM

initial_peers = [TODO_put_one_or_more_server_addresses_here]  # e.g. ["/ip4/127.0.0.1/tcp/more/stuff/here"]
tokenizer = transformers.BloomTokenizerFast.from_pretrained("bigscience/bloom-petals")
model = DistributedBloomForCausalLM.from_pretrained(
  "bigscience/bloom-petals", initial_peers=initial_peers, low_cpu_mem_usage=True, torch_dtype=torch.float16
)

inputs = tokenizer("a cat sat", return_tensors="pt")["input_ids"]
# use max_new_tokens instead of max_length 
remote_outputs = model.generate(inputs, max_new_tokens=50)
print(tokenizer.decode(remote_outputs[0]))
```

And the server reports an error.
```
Feb 06 16:14:16.227 [INFO] rpc_inference.open(blocks=0:4, remote_peer=...7c6z7M)
Feb 06 16:14:16.228 [INFO] rpc_inference.wait_for_alloc(size=0.04 GiB), already used 0.00/1.00 GiB (0.0%)
Feb 06 16:14:16.230 [INFO] rpc_inference.alloc(size=0.04 GiB)
Feb 06 16:14:16.249 [ERROR] [hivemind.moe.server.runtime.run:104] Caught indices should be either on cpu or on the same device as the indexed tensor (cuda:1), attempting to recover
Traceback (most recent call last):
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/hivemind/moe/server/runtime.py", line 91, in run
    outputs = pool.process_func(*batch)
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/backend.py", line 175, in __call__
    (hidden_states,) = self.backends[inference_info.uid].inference_step(hidden_states, hypo_ids, inference_info)
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/backend.py", line 92, in inference_step
    self._reorder_cache_inplace(cache_tensors, hypo_ids)
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/backend.py", line 102, in _reorder_cache_inplace
    cache_tensor[...] = cache_tensor[hypo_ids]  # in-place reorder cache by hypo ids
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
Feb 06 16:14:16.250 [INFO] rpc_inference.close(blocks=0:4, remote_peer=...7c6z7M)
Feb 06 16:14:16.250 [WARN] [hivemind.p2p.p2p_daemon._process_stream:436] Handler failed with the exception:
Traceback (most recent call last):
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 427, in _process_stream
    async for response in handler(_read_stream(), context):
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 525, in _stream_handler
    async for item in output:
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/handler.py", line 178, in rpc_inference
    (hidden_states,) = await self.module_backends[requested_uids[0]].inference_pool.submit_task(
  File "/data/anaconda3/envs/petals/lib/python3.10/site-packages/hivemind/utils/mpfuture.py", line 294, in __await__
    return super().result()
  File "/data/anaconda3/envs/petals/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/data/anaconda3/envs/petals/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
```

**Comment by borzunov** [comment]
@mabuyun,

I'm afraid that your server still uses an older version of Petals. We have fixed this error in #249 by replacing the line `cache_tensor[...] = cache_tensor[hypo_ids]` with `cache_tensor[...] = cache_tensor[hypo_ids.to(cache_tensor.device)]`, but your traceback still shows the older line.

#249 was merged a few hours before I responded to you the last time, so I think it is likely that you haven't updated Petals correctly. Maybe you did it in a wrong Anaconda env, or you have a subdirectory with an older version of Petals in your current working directory (so that Python uses the older code).

Please switch to the correct Anaconda env and run the upgrade command again, forcing the upgrade explicitly:
```bash
pip install git+https://github.com/bigscience-workshop/petals
```

Once you do that, please check that update has happened by checking the line 102 in the file `/data/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/backend.py`. This line should be `cache_tensor[...] = cache_tensor[hypo_ids.to(cache_tensor.device)]`, not `cache_tensor[...] = cache_tensor[hypo_ids]`.

**Comment by mabuyun** [comment]
@borzunov 

Hi,

I have tested several examples summarized in the table below

<details><summary>run_server.sh</summary>
<p>

n: Number of gpus on the machine
m: Number of blocks in this server 


```bash
export CUDA_VISIBLE_DEVICES=0,1,...,n 
COMPRESSION=NONE
CACHE_SIZE="3.0GiB"
MAX_BLOCK_IDX=70

START_IDX=$1
END_IDX=`expr $START_IDX + m`
if [ $END_IDX -gt $MAX_BLOCK_IDX ]; then
    END_IDX=$MAX_BLOCK_IDX
fi

HF_HUB_OFFLINE=1 python3 -m petals.cli.run_server bigscience/bloom-petals --throughput 150 --attn_cache_size $CACHE_SIZE  --host_maddrs /ip4/0.0.0.0/tcp/0 --initial_peers $INITIAL_PEERS --compression $COMPRESSION  --torch_dtype float16 --load_in_8bit True --tensor_parallel_devices cuda:0 cuda:1 ... cuda:N --block_indices $START_IDX:$END_IDX
```

</p>
</details>

<details><summary>test_speed.py</summary>
<p>

```
import torch
import transformers
from petals import DistributedBloomForCausalLM
import time


initial_peers = [
    "/ip4/xxx/tcp/x/p2p/xxx"
]

s='''Compose a long masterpiece poem.<DRINKING ALONE WITH THE MOON>:
From a pot of wine among the flowers 
I drank alone. There was no one with me -- 
Till, raising my cup, I asked the bright moon 
To bring me my shadow and make us three. 
Alas, the moon was unable to drink 
And my shadow tagged me vacantly; 
But still for a while I had these friends 
To cheer me through the end of spring.... 
I sang. The moon encouraged me. 
I danced. My shadow tumbled after. 
As long as I knew, we were boon companions. 
And then I was drunk, and we lost one another. 
...Shall goodwill ever be secure? 
I watch the long road of the River of Stars
<Aircraft Carrier>:'''


init_t = time.time()
tokenizer = transformers.BloomTokenizerFast.from_pretrained("bigscience/bloom-petals")
model = DistributedBloomForCausalLM.from_pretrained(
    "bigscience/bloom-petals",
    initial_peers=init_peers,
    low_cpu_mem_usage=True,
    torch_dtype=torch.float16,
    device_map="auto",
)
def make_inputs(s):
    inputs = tokenizer(s, return_tensors="pt")["input_ids"]
    if torch.cuda.is_available():
        inputs = inputs.to("cuda")
    return inputs

loop = 5
tokens = 100
start_t = time.time()
print(f"init cost {start_t - init_t}")
for i in range(loop):
    tmp_t = time.time()
    inputs = make_inputs(s)
    with torch.no_grad():
        remote_outputs = model.generate(
            inputs,
            temperature=0.95,
            max_new_tokens=tokens,
            do_sample=True,
            top_p=0.7,
            length_penalty=1.0,
            no_repeat_ngram_size=3,
        )
        result = tokenizer.decode(remote_outputs[0])
    end_t = time.time()
    print(f"{i+1} cost {(end_t - tmp_t)/tokens}")
    print(result)

end_t = time.time()
print(f"{total} avg cost {(end_t - start_t)/(total)/tokens}")
```
</p>
</details>

Machine: The number of machines used to run the service
GPUS: Number of Gpus on each machine
Blocks: Number of blocks per machine
Speed: The model inference measures speed in s/token

| Machine | GPUS | Blocks | Speed | Comment |
|-|-|-|-|-|
|35|1|2|1.47s/token|Speed under the original configuration, not using parallelism|
|18|2|4|1.11||
|7|5|10|2.70||
|5|7|14|4.51||

After these tests, there is no speedup with using multi-GPU servers

**Comment by borzunov** [comment]
I'm closing this due to inactivity. Thanks again for posting the benchmarks! Feel free to reopen this if you need any help or you'd like to share more results.
