### ISSUE TITLE
Issue with "Getting started" Tutorial (PydanticSchemaGenerationError)

### ISSUE THREAD

**Issue by lacksfish** [bigscience-workshop/petals#359]
I've attempted to try petals using [this getting started link](https://colab.research.google.com/drive/1Ervk6HPNS6AYVr3xVdQnY5a-TjjmLCdQ?usp=sharing#scrollTo=VsXHWJLuowcn) from the README.md

Unfortunately, already when running the "A cat in French is" example, the following exception is thrown.

```
Traceback (most recent call last):
  File "/my/folder/path/main.py", line 3, in <module>
    from petals import DistributedBloomForCausalLM
  File "/my/folder/path/venv/lib/python3.10/site-packages/petals/__init__.py", line 3, in <module>
    import hivemind
  File "/my/folder/path/venv/lib/python3.10/site-packages/hivemind/__init__.py", line 12, in <module>
    from hivemind.optim import GradScaler, Optimizer, TrainingAverager
  File "/my/folder/path/venv/lib/python3.10/site-packages/hivemind/optim/__init__.py", line 2, in <module>
    from hivemind.optim.optimizer import Optimizer
  File "/my/folder/path/venv/lib/python3.10/site-packages/hivemind/optim/optimizer.py", line 16, in <module>
    from hivemind.optim.progress_tracker import LocalTrainingProgress, ProgressTracker
  File "/my/folder/path/venv/lib/python3.10/site-packages/hivemind/optim/progress_tracker.py", line 40, in <module>
    class TrainingProgressSchema(BaseModel):
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 174, in __new__
    complete_model_class(
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 431, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/main.py", line 533, in __get_pydantic_core_schema__
    return __handler(__source)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 280, in generate_schema
    return self._generate_schema_for_type(
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 301, in _generate_schema_for_type
    schema = self._generate_schema(obj)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 519, in _generate_schema
    return self._model_schema(obj)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 370, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 370, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 674, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 714, in _common_field_schema
    schema = self._apply_annotations(
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1405, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1487, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_std_types_schema.py", line 711, in __get_pydantic_core_schema__
    keys_schema = handler.generate_schema(self.keys_source_type)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 96, in generate_schema
    return self._generate_schema.generate_schema(__source_type)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 280, in generate_schema
    return self._generate_schema_for_type(
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 301, in _generate_schema_for_type
    schema = self._generate_schema(obj)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 586, in _generate_schema
    return self._arbitrary_type_schema(obj, obj)
  File "/my/folder/path/venv/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 638, in _arbitrary_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'hivemind.dht.schema.conbytes.<locals>.ConstrainedBytesWithRegex'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.0.3/u/schema-for-unknown-type

Process finished with exit code 1
```

Do I need to set `arbitrary_types_allowed=True`? If so, where?

**Comment by lacksfish** [comment]
Made some progess with using

```pip install git+https://github.com/bigscience-workshop/petals```

instead of
```pip install petals```

Maybe pip is providing an outdated version? idk

**Comment by borzunov** [comment]
Hi @lacksfish,

Sorry, we've updated the website and "Try now in Colab" link but forgot to update the 2nd "Getting started" link below. Here's the latest [notebook](https://colab.research.google.com/drive/1uCphNY7gfAUkdDrTx21dZZwCOUDCMPw8?usp=sharing).
