### ISSUE TITLE
chat.petals repeatedly dies with errors

### ISSUE THREAD

**Issue by pleabargain** [bigscience-workshop/petals#382]
![image](https://github.com/bigscience-workshop/petals/assets/640846/1170806f-ed2f-42d8-8796-0968acaad84e)

Request failed. [Retry](http://chat.petals.ml/#)
Traceback (most recent call last):
  File "/home/borzunov/chat.petals.ml/websocket_api.py", line 51, in ws_api_generate
    outputs = model.generate(
  File "/home/borzunov/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/borzunov/.local/lib/python3.10/site-packages/petals/client/remote_generation.py", line 171, in generate
    hidden_state = session.step(hidden_state, prompts=intermediate_prompts, hypo_ids=hypo_ids)[:, -1]
  File "/home/borzunov/.local/lib/python3.10/site-packages/petals/client/inference_session.py", line 304, in step
    inputs = server_session.step(
  File "/home/borzunov/.local/lib/python3.10/site-packages/petals/client/inference_session.py", line 147, in step
    outputs_serialized = RemoteExpertWorker.run_coroutine(
  File "/home/borzunov/.local/lib/python3.10/site-packages/hivemind/moe/client/remote_expert_worker.py", line 36, in run_coroutine
    return future if return_future else future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/borzunov/.local/lib/python3.10/site-packages/petals/client/inference_session.py", line 182, in _step
    return await asyncio.wait_for(anext(self._outputs_stream), self.config.request_timeout)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/borzunov/.local/lib/python3.10/site-packages/hivemind/utils/asyncio.py", line 31, in anext
    return await aiter.__anext__()
  File "/home/borzunov/.local/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 489, in _read_from_stream
    raise P2PHandlerError(f"Failed to call handler `{name}` at {peer_id}: {err.message}")
hivemind.p2p.p2p_daemon_bindings.utils.P2PHandlerError: Failed to call handler `TransformerConnectionHandler.rpc_inference` at 12D3KooWDU6XWm1CBCkXrC7hfGgjWWhkJMSBLCVoku2f1kQCvZmZ: CUDA out of memory. Tried to allocate 688.00 MiB (GPU 0; 23.69 GiB total capacity; 22.82 GiB already allocated; 87.94 MiB free; 23.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by justheuristic** [comment]
This might be due to us accidentally spilling testing instances into production, lemme ask around

**Comment by pleabargain** [comment]
site is not working so I can't tell you :)
![image](https://github.com/bigscience-workshop/petals/assets/640846/7912be48-8aa0-4e3e-b572-16e9e008a3f4)

**Comment by borzunov** [comment]
Hi @pleabargain,

We're having issues with the domain registrar, see here https://github.com/bigscience-workshop/petals/issues/386#issuecomment-1643512385

You can access the chat app at http://143.244.175.95 until the domains issues get resolved.

**Comment by pleabargain** [comment]
Many thanks sir!

**Comment by borzunov** [comment]
@pleabargain, we've moved to a new domain, see https://chat.petals.dev

Let us know if you have any other issues!

**Comment by pleabargain** [comment]
thank you!

**Comment by borzunov** [comment]
@pleabargain Indeed, thanks for pointing this out :)

**Comment by pleabargain** [comment]
thank you! Your code is fascinating!
