### ISSUE TITLE
CUDA out of memory (Petals Server via Docker)

### ISSUE THREAD

**Issue by ivangabriele** [bigscience-workshop/petals#413]
When running `learningathome/petals:main` Docker image, I regularly have `CUDA out of memory` errors. I admit my GPU is old (Geforce RTX 2070), is it because of that?

```
➜  Binaries docker run -p 31330:31330 --ipc host --gpus all --volume petals-cache:/cache --rm learningathome/petals:main python -m petals.cli.run_server --port 31330 enoch/llama-65b-hf --adapters timdettmers/guanaco-65b --public_name ivangabriele
Jul 23 13:07:15.639 [INFO] Running Petals 2.0.0.post3
Downloading (…)lve/main/config.json: 100%|██████████| 509/509 [00:00<00:00, 3.93MB/s]
Jul 23 13:07:16.644 [INFO] Make sure you follow the LLaMA's terms of use: https://bit.ly/llama2-license for LLaMA 2, https://bit.ly/llama-license for LLaMA 1
Jul 23 13:07:16.644 [INFO] Using DHT prefix: llama-65b-hf
Jul 23 13:07:27.680 [INFO] This server is accessible directly
Jul 23 13:07:31.666 [INFO] Connecting to the public swarm
Jul 23 13:07:31.667 [INFO] Running a server on ['/ip4/172.17.0.2/tcp/31330/p2p/12D3KooWMPTUGXTVsLJ5KK2uXKqp9wnSCWHU1bbotHNnX5wsFTbq', '/ip4/127.0.0.1/tcp/31330/p2p/12D3KooWMPTUGXTVsLJ5KK2uXKqp9wnSCWHU1bbotHNnX5wsFTbq']
Jul 23 13:07:31.688 [INFO] Model weights are loaded in float16, quantized to nf4 format
Downloading (…)/adapter_config.json: 100%|██████████| 425/425 [00:00<00:00, 3.36MB/s]
Downloading (…)er_model.safetensors:   0%|          | 0.00/3.20G [00:00<?, ?B/s]Jul 23 13:07:33.651 [INFO] Reachability service started
Downloading (…)er_model.safetensors: 100%|██████████| 3.20G/3.20G [19:12<00:00, 2.78MB/s]
Jul 23 13:26:45.352 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 13:26:45.367 [INFO] Loaded adapter timdettmers/guanaco-65b for block 0
Jul 23 13:26:45.368 [INFO] Server will fill all your GPU memory with 9 transformer blocks. If you want to leave some free GPU memory, please specify a lesser --num_blocks manually
Jul 23 13:26:45.368 [INFO] Attention cache for all blocks will consume up to 2.25 GiB
Jul 23 13:26:45.368 [INFO] Loading throughput info
Jul 23 13:26:45.369 [INFO] Reporting throughput: 762.9 tokens/sec for 9 blocks
Jul 23 13:26:57.699 [INFO] Announced that blocks [60, 61, 62, 63, 64, 65, 66, 67, 68] are joining

...

Jul 23 14:46:23.082 [INFO] Started
Jul 23 14:48:00.717 [INFO] Swarm balance quality: 66.5%
Jul 23 14:48:00.718 [INFO] Swarm is imbalanced, server will load other blocks
Jul 23 14:48:01.864 [INFO] Announced that blocks ['llama-65b-hf.70', 'llama-65b-hf.71', 'llama-65b-hf.72', 'llama-65b-hf.73', 'llama-65b-hf.74', 'llama-65b-hf.75', 'llama-65b-hf.76', 'llama-65b-hf.77', 'llama-65b-hf.78'] are offline
Jul 23 14:48:03.793 [INFO] Shutting down
Jul 23 14:48:03.797 [INFO] Module container shut down successfully
Jul 23 14:48:03.895 [INFO] Cleaning up, left 0.1 GiB allocated memory, 2.9 GiB reserved memory
Jul 23 14:48:05.344 [INFO] Announced that blocks [71, 72, 73, 74, 75, 76, 77, 78, 79] are joining
Jul 23 14:48:06.260 [INFO] Loaded enoch/llama-65b-hf block 71, <All keys matched successfully>
Jul 23 14:48:16.332 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:48:16.492 [INFO] Loaded adapter timdettmers/guanaco-65b for block 71
Jul 23 14:48:17.285 [INFO] Loaded enoch/llama-65b-hf block 72, <All keys matched successfully>
Jul 23 14:48:27.298 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:48:27.387 [INFO] Loaded adapter timdettmers/guanaco-65b for block 72
Jul 23 14:48:28.179 [INFO] Loaded enoch/llama-65b-hf block 73, <All keys matched successfully>
Jul 23 14:48:38.186 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:48:38.305 [INFO] Loaded adapter timdettmers/guanaco-65b for block 73
Jul 23 14:48:39.104 [INFO] Loaded enoch/llama-65b-hf block 74, <All keys matched successfully>
Jul 23 14:48:49.110 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:48:49.213 [INFO] Loaded adapter timdettmers/guanaco-65b for block 74
Jul 23 14:48:50.057 [INFO] Loaded enoch/llama-65b-hf block 75, <All keys matched successfully>
Jul 23 14:49:00.246 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:49:00.421 [INFO] Loaded adapter timdettmers/guanaco-65b for block 75
Jul 23 14:49:01.296 [INFO] Loaded enoch/llama-65b-hf block 76, <All keys matched successfully>
Jul 23 14:49:11.408 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:49:11.554 [INFO] Loaded adapter timdettmers/guanaco-65b for block 76
Jul 23 14:49:12.400 [INFO] Loaded enoch/llama-65b-hf block 77, <All keys matched successfully>
Jul 23 14:49:22.546 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:49:22.662 [INFO] Loaded adapter timdettmers/guanaco-65b for block 77
Jul 23 14:49:23.533 [INFO] Loaded enoch/llama-65b-hf block 78, <All keys matched successfully>
Jul 23 14:49:33.859 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:49:34.023 [INFO] Loaded adapter timdettmers/guanaco-65b for block 78
Jul 23 14:49:35.221 [INFO] Loaded enoch/llama-65b-hf block 79, <All keys matched successfully>
Jul 23 14:49:45.574 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 14:49:45.677 [INFO] Loaded adapter timdettmers/guanaco-65b for block 79
Jul 23 14:49:45.965 [INFO] Server is reachable from the Internet. It will appear at https://health.petals.dev soon
Jul 23 14:49:47.154 [INFO] Started
Jul 23 14:53:46.172 [INFO] rpc_inference.open(blocks=72:80, remote_peer=...TMdbyL)
Jul 23 14:53:46.173 [INFO] rpc_inference.wait_for_alloc(size=0.50 GiB), already used 0.00/2.25 GiB (0.0%)
Jul 23 14:53:46.174 [INFO] rpc_inference.alloc(size=0.50 GiB)
Jul 23 14:53:46.280 [ERROR] [hivemind.moe.server.runtime.run:104] Caught CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 71.50 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF, attempting to recover
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/moe/server/runtime.py", line 91, in run
    outputs = pool.process_func(*batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/petals/src/petals/server/backend.py", line 197, in __call__
    (hidden_states,) = self.backends[inference_info.uid].inference_step(hidden_states, hypo_ids, inference_info)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/petals/src/petals/server/backend.py", line 113, in inference_step
    hidden_states, new_kvs = self.module.forward(hidden_states, layer_past=layer_past, use_cache=True)
  File "/opt/conda/lib/python3.10/site-packages/tensor_parallel/tensor_parallel.py", line 99, in forward
    return [self.module_shards[0](*args, **kwargs)][self.output_device_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/petals/src/petals/models/llama/block.py", line 52, in forward
    outputs = super().forward(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 363, in forward
    attn_output = self.o_proj(attn_output)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/tuners/lora.py", line 1123, in forward
    result = super().forward(x)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 221, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 516, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, state).to(A.dtype).t(), bias)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/functional.py", line 908, in dequantize_4bit
    out = torch.empty(shape, dtype=dtype, device=A.device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 71.50 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Jul 23 14:53:46.285 [INFO] rpc_inference.close(blocks=72:80, remote_peer=...TMdbyL)
Jul 23 14:53:46.285 [WARN] [hivemind.p2p.p2p_daemon._process_stream:440] Handler failed with the exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 431, in _process_stream
    async for response in handler(_read_stream(), context):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 529, in _stream_handler
    async for item in output:
  File "/home/petals/src/petals/server/handler.py", line 219, in rpc_inference
    (hidden_states,) = await self.module_backends[requested_uids[0]].inference_pool.submit_task(
  File "/opt/conda/lib/python3.10/site-packages/hivemind/utils/mpfuture.py", line 298, in __await__
    return super().result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 71.50 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Jul 23 14:53:48.303 [INFO] rpc_inference.open(blocks=72:80, remote_peer=...TMdbyL)
Jul 23 14:53:48.304 [INFO] rpc_inference.wait_for_alloc(size=0.50 GiB), already used 0.00/2.25 GiB (0.0%)
Jul 23 14:53:48.305 [INFO] rpc_inference.alloc(size=0.50 GiB)
Jul 23 14:53:48.346 [ERROR] [hivemind.moe.server.runtime.run:104] Caught CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 50.88 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF, attempting to recover
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/moe/server/runtime.py", line 91, in run
    outputs = pool.process_func(*batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/petals/src/petals/server/backend.py", line 197, in __call__
    (hidden_states,) = self.backends[inference_info.uid].inference_step(hidden_states, hypo_ids, inference_info)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/petals/src/petals/server/backend.py", line 113, in inference_step
    hidden_states, new_kvs = self.module.forward(hidden_states, layer_past=layer_past, use_cache=True)
  File "/opt/conda/lib/python3.10/site-packages/tensor_parallel/tensor_parallel.py", line 99, in forward
    return [self.module_shards[0](*args, **kwargs)][self.output_device_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/petals/src/petals/models/llama/block.py", line 52, in forward
    outputs = super().forward(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 363, in forward
    attn_output = self.o_proj(attn_output)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/tuners/lora.py", line 1123, in forward
    result = super().forward(x)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 221, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 516, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, state).to(A.dtype).t(), bias)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/functional.py", line 908, in dequantize_4bit
    out = torch.empty(shape, dtype=dtype, device=A.device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 50.88 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Jul 23 14:53:48.347 [INFO] rpc_inference.close(blocks=72:80, remote_peer=...TMdbyL)
Jul 23 14:53:48.348 [WARN] [hivemind.p2p.p2p_daemon._process_stream:440] Handler failed with the exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 431, in _process_stream
    async for response in handler(_read_stream(), context):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 529, in _stream_handler
    async for item in output:
  File "/home/petals/src/petals/server/handler.py", line 219, in rpc_inference
    (hidden_states,) = await self.module_backends[requested_uids[0]].inference_pool.submit_task(
  File "/opt/conda/lib/python3.10/site-packages/hivemind/utils/mpfuture.py", line 298, in __await__
    return super().result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 50.88 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Jul 23 14:53:51.406 [INFO] rpc_inference.open(blocks=72:80, remote_peer=...TMdbyL)
Jul 23 14:53:51.407 [INFO] rpc_inference.wait_for_alloc(size=0.50 GiB), already used 0.00/2.25 GiB (0.0%)
Jul 23 14:53:51.408 [INFO] rpc_inference.alloc(size=0.50 GiB)
Jul 23 14:53:51.456 [ERROR] [hivemind.moe.server.runtime.run:104] Caught CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 44.19 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF, attempting to recover
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/moe/server/runtime.py", line 91, in run
    outputs = pool.process_func(*batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/petals/src/petals/server/backend.py", line 197, in __call__
    (hidden_states,) = self.backends[inference_info.uid].inference_step(hidden_states, hypo_ids, inference_info)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/petals/src/petals/server/backend.py", line 113, in inference_step
    hidden_states, new_kvs = self.module.forward(hidden_states, layer_past=layer_past, use_cache=True)
  File "/opt/conda/lib/python3.10/site-packages/tensor_parallel/tensor_parallel.py", line 99, in forward
    return [self.module_shards[0](*args, **kwargs)][self.output_device_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/petals/src/petals/models/llama/block.py", line 52, in forward
    outputs = super().forward(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 363, in forward
    attn_output = self.o_proj(attn_output)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/tuners/lora.py", line 1123, in forward
    result = super().forward(x)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 221, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 579, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 516, in forward
    output = torch.nn.functional.linear(A, F.dequantize_4bit(B, state).to(A.dtype).t(), bias)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/functional.py", line 908, in dequantize_4bit
    out = torch.empty(shape, dtype=dtype, device=A.device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 44.19 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Jul 23 14:53:51.458 [INFO] rpc_inference.close(blocks=72:80, remote_peer=...TMdbyL)
Jul 23 14:53:51.458 [WARN] [hivemind.p2p.p2p_daemon._process_stream:440] Handler failed with the exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 431, in _process_stream
    async for response in handler(_read_stream(), context):
  File "/opt/conda/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 529, in _stream_handler
    async for item in output:
  File "/home/petals/src/petals/server/handler.py", line 219, in rpc_inference
    (hidden_states,) = await self.module_backends[requested_uids[0]].inference_pool.submit_task(
  File "/opt/conda/lib/python3.10/site-packages/hivemind/utils/mpfuture.py", line 298, in __await__
    return super().result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.46 GiB already allocated; 44.19 MiB free; 4.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Jul 23 15:00:31.415 [INFO] Swarm balance quality: 43.0%
Jul 23 15:00:31.415 [INFO] Swarm is imbalanced, server will load other blocks
Jul 23 15:00:33.042 [INFO] Announced that blocks ['llama-65b-hf.71', 'llama-65b-hf.72', 'llama-65b-hf.73', 'llama-65b-hf.74', 'llama-65b-hf.75', 'llama-65b-hf.76', 'llama-65b-hf.77', 'llama-65b-hf.78', 'llama-65b-hf.79'] are offline
Jul 23 15:00:34.844 [INFO] Shutting down
Jul 23 15:00:34.848 [INFO] Module container shut down successfully
Jul 23 15:00:34.928 [INFO] Cleaning up, left 0.6 GiB allocated memory, 3.6 GiB reserved memory
Jul 23 15:00:39.556 [INFO] Announced that blocks [70, 71, 72, 73, 74, 75, 76, 77, 78] are joining
Jul 23 15:00:40.504 [INFO] Loaded enoch/llama-65b-hf block 70, <All keys matched successfully>
Jul 23 15:00:50.748 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:00:50.871 [INFO] Loaded adapter timdettmers/guanaco-65b for block 70
Jul 23 15:00:51.689 [INFO] Loaded enoch/llama-65b-hf block 71, <All keys matched successfully>
Jul 23 15:01:01.676 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:01:01.813 [INFO] Loaded adapter timdettmers/guanaco-65b for block 71
Jul 23 15:01:02.672 [INFO] Loaded enoch/llama-65b-hf block 72, <All keys matched successfully>
Jul 23 15:01:12.673 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:01:12.833 [INFO] Loaded adapter timdettmers/guanaco-65b for block 72
Jul 23 15:01:13.690 [INFO] Loaded enoch/llama-65b-hf block 73, <All keys matched successfully>
Jul 23 15:01:23.692 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:01:23.843 [INFO] Loaded adapter timdettmers/guanaco-65b for block 73
Jul 23 15:01:24.668 [INFO] Loaded enoch/llama-65b-hf block 74, <All keys matched successfully>
Jul 23 15:01:34.915 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:01:35.003 [INFO] Loaded adapter timdettmers/guanaco-65b for block 74
Jul 23 15:01:35.860 [INFO] Loaded enoch/llama-65b-hf block 75, <All keys matched successfully>
Jul 23 15:01:45.881 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:01:46.013 [INFO] Loaded adapter timdettmers/guanaco-65b for block 75
Jul 23 15:01:46.877 [INFO] Loaded enoch/llama-65b-hf block 76, <All keys matched successfully>
Jul 23 15:01:56.991 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:01:57.113 [INFO] Loaded adapter timdettmers/guanaco-65b for block 76
Jul 23 15:01:57.958 [INFO] Loaded enoch/llama-65b-hf block 77, <All keys matched successfully>
Jul 23 15:02:08.157 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:02:08.273 [INFO] Loaded adapter timdettmers/guanaco-65b for block 77
Jul 23 15:02:09.183 [INFO] Loaded enoch/llama-65b-hf block 78, <All keys matched successfully>
Jul 23 15:02:19.298 [INFO] Adapter timdettmers/guanaco-65b has dropout enabled, this server will disable dropout
Jul 23 15:02:19.480 [INFO] Loaded adapter timdettmers/guanaco-65b for block 78
Jul 23 15:02:20.069 [INFO] Server is reachable from the Internet. It will appear at https://health.petals.dev soon
Jul 23 15:02:21.321 [INFO] Started
```

**Comment by borzunov** [comment]
Hi @ivangabriele,

Our formula for the number of blocks may be imperfect - apparently, it suggested too many blocks for you to host. You can host 7-8 blocks instead of 9 by specifying `--num_blocks 7` or `--num_blocks 8` - this should address OOMs. Let us know if it helps.

**Comment by ivangabriele** [comment]
Yes, that's stable now! Thank you ^^.
