### ISSUE TITLE
 local time must be within 3 seconds  of others

### ISSUE THREAD

**Issue by ryanshrott** [bigscience-workshop/petals#433]
What does this mean? How to fix it?

Traceback (most recent call last):
  File "/mnt/c/users/ryans/documents/petals_mongo_script.py", line 17, in <module>
    model = AutoDistributedModelForCausalLM.from_pretrained(model_name)
  File "/home/ryan/.local/lib/python3.10/site-packages/petals/utils/auto_config.py", line 49, in from_pretrained
    return proper_cls.from_pretrained(model_name_or_path, *args, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/petals/client/from_pretrained.py", line 37, in from_pretrained
    return super().from_pretrained(
  File "/home/ryan/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/petals/models/llama/model.py", line 117, in __init__
    self.model = DistributedLlamaModel(config)
  File "/home/ryan/.local/lib/python3.10/site-packages/petals/models/llama/model.py", line 34, in __init__
    self.layers = RemoteSequential(config, dht=dht)
  File "/home/ryan/.local/lib/python3.10/site-packages/petals/client/remote_sequential.py", line 45, in __init__
    sequence_manager = RemoteSequenceManager(config, block_uids, dht=dht, **kwargs)
  File "/home/ryan/.local/lib/python3.10/site-packages/petals/client/routing/sequence_manager.py", line 101, in __init__
    dht = DHT(
  File "/home/ryan/.local/lib/python3.10/site-packages/hivemind/dht/dht.py", line 88, in __init__
    self.run_in_background(await_ready=await_ready)
  File "/home/ryan/.local/lib/python3.10/site-packages/hivemind/dht/dht.py", line 148, in run_in_background
    self.wait_until_ready(timeout)
  File "/home/ryan/.local/lib/python3.10/site-packages/hivemind/dht/dht.py", line 151, in wait_until_ready
    self._ready.result(timeout=timeout)
  File "/home/ryan/.local/lib/python3.10/site-packages/hivemind/utils/mpfuture.py", line 262, in result
    return super().result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
hivemind.dht.protocol.ValidationError: local time must be within 3 seconds  of others(local: 1691158862.35442, peer: 1691160179.92986)

**Comment by borzunov** [comment]
Hi @ryanshrott,

Please run `ntpdate pool.ntp.org` to fix it. This happens because WSL has time precision issues by default.

**Comment by borzunov** [comment]
See solutions for this and other issues on the ["Troubleshooting"](https://github.com/bigscience-workshop/petals/wiki/Troubleshooting) page.

Let us know if you have any other questions!
